// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	common "grpc.go/protos/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Addresses            []*Addr  `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddresses() []*Addr {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type UserListsReq struct {
	Page                 *common.Page `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserListsReq) Reset()         { *m = UserListsReq{} }
func (m *UserListsReq) String() string { return proto.CompactTextString(m) }
func (*UserListsReq) ProtoMessage()    {}
func (*UserListsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserListsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListsReq.Unmarshal(m, b)
}
func (m *UserListsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListsReq.Marshal(b, m, deterministic)
}
func (m *UserListsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListsReq.Merge(m, src)
}
func (m *UserListsReq) XXX_Size() int {
	return xxx_messageInfo_UserListsReq.Size(m)
}
func (m *UserListsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListsReq proto.InternalMessageInfo

func (m *UserListsReq) GetPage() *common.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type UserListsResp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListsResp) Reset()         { *m = UserListsResp{} }
func (m *UserListsResp) String() string { return proto.CompactTextString(m) }
func (*UserListsResp) ProtoMessage()    {}
func (*UserListsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserListsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListsResp.Unmarshal(m, b)
}
func (m *UserListsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListsResp.Marshal(b, m, deterministic)
}
func (m *UserListsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListsResp.Merge(m, src)
}
func (m *UserListsResp) XXX_Size() int {
	return xxx_messageInfo_UserListsResp.Size(m)
}
func (m *UserListsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListsResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListsResp proto.InternalMessageInfo

func (m *UserListsResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*UserListsReq)(nil), "users.UserListsReq")
	proto.RegisterType((*UserListsResp)(nil), "users.UserListsResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x9a, 0x20, 0xf5, 0x52, 0x18, 0x0e, 0x86, 0x28, 0x93, 0xc9, 0x14, 0x16, 0x07,
	0x19, 0x56, 0x06, 0xc6, 0x4a, 0x08, 0x21, 0x4b, 0xfd, 0x01, 0xa6, 0x3e, 0x59, 0x0c, 0xc1, 0xc6,
	0x57, 0xfe, 0x3f, 0xb2, 0x0d, 0xa2, 0xa8, 0xdb, 0xf9, 0xde, 0x7b, 0xfe, 0x9e, 0x0d, 0xf0, 0xc5,
	0x14, 0x65, 0x88, 0xfe, 0xe0, 0xb1, 0x4d, 0x33, 0x0f, 0xc2, 0xc5, 0xb0, 0x97, 0xce, 0xcf, 0x79,
	0xcb, 0xf3, 0xde, 0x2f, 0x8b, 0xff, 0x98, 0x83, 0x71, 0x54, 0x8c, 0x03, 0x18, 0x6b, 0x7f, 0x42,
	0xe3, 0x0e, 0x9a, 0x1d, 0x53, 0xc4, 0x4b, 0xa8, 0xb7, 0xb6, 0xaf, 0x44, 0x35, 0xb5, 0xba, 0xde,
	0x5a, 0x44, 0x68, 0x5e, 0xcc, 0x42, 0x7d, 0x2d, 0xaa, 0x69, 0xad, 0xf3, 0x8c, 0xb7, 0xb0, 0x4e,
	0x49, 0x62, 0x26, 0xee, 0x57, 0x62, 0x35, 0x75, 0xaa, 0x93, 0x19, 0x2a, 0x9f, 0xac, 0x8d, 0xfa,
	0x4f, 0x1d, 0xef, 0x60, 0x93, 0xae, 0x7d, 0x7e, 0xe7, 0x03, 0x6b, 0xfa, 0x44, 0x01, 0x4d, 0x2a,
	0x90, 0x01, 0x9d, 0xda, 0xc8, 0x52, 0x4a, 0xbe, 0x1a, 0x47, 0x3a, 0x2b, 0xa3, 0x82, 0x8b, 0xa3,
	0x04, 0x07, 0xbc, 0x81, 0xf2, 0xa0, 0xbe, 0xfa, 0x47, 0x4a, 0x26, 0x5d, 0x14, 0xf5, 0x08, 0x6d,
	0x3a, 0x32, 0x3e, 0x40, 0x9b, 0x83, 0x78, 0x75, 0xe4, 0xfa, 0x85, 0x0f, 0xd7, 0xa7, 0x4b, 0x0e,
	0xe3, 0xd9, 0xdb, 0x79, 0xfe, 0x82, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x10, 0xf9,
	0x98, 0x45, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Lists(ctx context.Context, in *UserListsReq, opts ...grpc.CallOption) (*UserListsResp, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Lists(ctx context.Context, in *UserListsReq, opts ...grpc.CallOption) (*UserListsResp, error) {
	out := new(UserListsResp)
	err := c.cc.Invoke(ctx, "/users.Users/Lists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Lists(context.Context, *UserListsReq) (*UserListsResp, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Lists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Lists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/Lists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Lists(ctx, req.(*UserListsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lists",
			Handler:    _Users_Lists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
